"use client"

// ============================================================================
// /reset-password?token=<token>[&_storefront=<slug>]
//
// Token-based password reset page.  The link is generated by
// POST /api/core/storefront/auth/forgot-password and emailed to the customer.
//
// Flow:
//   1. Read `token` (and optional `_storefront`) from the URL.
//   2. Validate the token against the backend on mount.
//   3. Show:
//        LOADING   → validating token
//        INVALID   → "Link expired or already used" + link to request new one
//        FORM      → New Password + Confirm Password
//        SUCCESS   → "Password updated" + redirect to storefront
// ============================================================================

import { useState, useEffect, Suspense } from "react"
import { useSearchParams } from "next/navigation"
import { CheckCircle2, Eye, EyeOff, Lock, Loader2, AlertCircle } from "lucide-react"

const PASSWORD_RULES = [
  { label: "8+ characters", test: (p: string) => p.length >= 8 },
  { label: "Uppercase",     test: (p: string) => /[A-Z]/.test(p) },
  { label: "Lowercase",     test: (p: string) => /[a-z]/.test(p) },
  { label: "Number",        test: (p: string) => /[0-9]/.test(p) },
  { label: "Special char",  test: (p: string) => /[^A-Za-z0-9]/.test(p) },
]

type PageState = "loading" | "invalid" | "form" | "success"

function ResetPasswordInner() {
  const searchParams = useSearchParams()
  const token        = searchParams.get("token") ?? ""
  const slug         = searchParams.get("_storefront") ?? ""

  const [state,      setState]     = useState<PageState>("loading")
  const [password,   setPassword]  = useState("")
  const [confirm,    setConfirm]   = useState("")
  const [showPw,     setShowPw]    = useState(false)
  const [showConf,   setShowConf]  = useState(false)
  const [error,      setError]     = useState("")
  const [loading,    setLoading]   = useState(false)

  const rules      = PASSWORD_RULES.map(r => ({ ...r, passed: r.test(password) }))
  const allPassed  = rules.every(r => r.passed)
  const pwMatch    = password === confirm && confirm.length > 0
  const isValid    = allPassed && pwMatch

  const storefrontUrl = slug
    ? `https://${slug}.${process.env.NEXT_PUBLIC_STOREFRONT_DOMAIN ?? "quantixtechnology.in"}`
    : "/"

  // Validate the token on mount
  useEffect(() => {
    if (!token) { setState("invalid"); return }

    fetch("/api/core/storefront/auth/validate-reset-token", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ token }),
    })
      .then(r => r.json())
      .then(json => setState(json.valid ? "form" : "invalid"))
      .catch(() => setState("invalid"))
  }, [token])

  async function handleReset() {
    if (!isValid || loading) return
    setLoading(true); setError("")
    try {
      const res  = await fetch("/api/core/storefront/auth/reset-password-via-token", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, password, confirmPassword: confirm }),
      })
      const json = await res.json()
      if (!json.success) throw new Error(json.error || "Reset failed")

      // Store the session returned by reset-password-via-token
      if (json.data?.accessToken) {
        localStorage.setItem("quantix_auth_token", json.data.accessToken)
        if (json.data.refreshToken) localStorage.setItem("quantix_auth_refresh_token", json.data.refreshToken)
        if (json.data.user) {
          localStorage.setItem("quantix_auth_user", JSON.stringify(json.data.user))
          localStorage.setItem("quantix_auth_role", json.data.user.role ?? "CUSTOMER")
          if (json.data.user.businessId) localStorage.setItem("quantix_auth_business_id", json.data.user.businessId)
        }
      }

      setState("success")
      // Redirect to storefront after 2 seconds
      setTimeout(() => { window.location.href = storefrontUrl }, 2000)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to reset password")
    } finally { setLoading(false) }
  }

  // ── Loading ──────────────────────────────────────────────────────────────
  if (state === "loading") {
    return (
      <CenteredCard>
        <div className="flex flex-col items-center gap-3 py-6">
          <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
          <p className="text-sm text-gray-500">Validating reset link…</p>
        </div>
      </CenteredCard>
    )
  }

  // ── Invalid / expired ────────────────────────────────────────────────────
  if (state === "invalid") {
    return (
      <CenteredCard title="Link Expired">
        <div className="flex flex-col items-center gap-4 py-2">
          <div className="w-14 h-14 rounded-2xl bg-red-50 flex items-center justify-center">
            <AlertCircle className="w-7 h-7 text-red-500" />
          </div>
          <div className="text-center">
            <p className="text-sm text-gray-600 leading-relaxed">
              This password reset link has expired or has already been used.
            </p>
            <p className="text-xs text-gray-400 mt-1">Links are valid for 15 minutes and can only be used once.</p>
          </div>
          <a href={storefrontUrl}
            className="text-sm font-medium text-emerald-600 hover:text-emerald-700 underline underline-offset-2">
            Back to store
          </a>
        </div>
      </CenteredCard>
    )
  }

  // ── Success ──────────────────────────────────────────────────────────────
  if (state === "success") {
    return (
      <CenteredCard title="Password Updated">
        <div className="flex flex-col items-center gap-4 py-2">
          <CheckCircle2 className="w-14 h-14 text-emerald-500" />
          <div className="text-center">
            <p className="text-sm font-semibold text-gray-900">Password updated successfully!</p>
            <p className="text-xs text-gray-500 mt-1">Redirecting you to the store…</p>
          </div>
        </div>
      </CenteredCard>
    )
  }

  // ── Form ─────────────────────────────────────────────────────────────────
  return (
    <CenteredCard title="Set New Password">
      <p className="text-xs text-gray-500 mb-4">
        Choose a strong password for your account.
      </p>

      {error && (
        <div className="flex items-start gap-2 bg-red-50 border border-red-100 rounded-xl px-3 py-2 mb-3">
          <AlertCircle className="w-3.5 h-3.5 text-red-500 shrink-0 mt-0.5" />
          <p className="text-xs text-red-700">{error}</p>
        </div>
      )}

      <PasswordField
        value={password} show={showPw}
        onChange={v => { setPassword(v); setError("") }}
        onToggle={() => setShowPw(v => !v)}
        placeholder="New Password *"
      />
      {password.length > 0 && (
        <div className="grid grid-cols-2 gap-1 mb-3">
          {rules.map(r => (
            <div key={r.label} className="flex items-center gap-1">
              <CheckCircle2 className={`w-2.5 h-2.5 shrink-0 ${r.passed ? "text-emerald-500" : "text-gray-300"}`} />
              <span className={`text-[9px] ${r.passed ? "text-emerald-700" : "text-gray-400"}`}>{r.label}</span>
            </div>
          ))}
        </div>
      )}

      <PasswordField
        value={confirm} show={showConf}
        onChange={v => { setConfirm(v); setError("") }}
        onToggle={() => setShowConf(v => !v)}
        placeholder="Confirm Password *"
      />
      {confirm.length > 0 && !pwMatch && (
        <p className="text-[10px] text-red-500 mb-2">Passwords do not match</p>
      )}

      <div className="mt-2">
        <button
          onClick={handleReset}
          disabled={!isValid || loading}
          className="w-full h-11 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-40 text-white font-bold text-sm rounded-xl flex items-center justify-center gap-2 transition-all"
        >
          {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : "Reset Password"}
        </button>
      </div>

      <div className="text-center mt-4">
        <a href={storefrontUrl} className="text-xs text-gray-400 hover:text-gray-600 underline underline-offset-2">
          Back to store
        </a>
      </div>
    </CenteredCard>
  )
}

// ── Layout helpers ────────────────────────────────────────────────────────────

function CenteredCard({ children, title }: { children: React.ReactNode; title?: string }) {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4 py-12">
      <div className="w-full max-w-sm">
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm p-8">
          <div className="text-center mb-6">
            <div className="w-12 h-12 rounded-2xl bg-emerald-600 flex items-center justify-center text-white text-lg font-bold mx-auto mb-3">
              Q
            </div>
            {title && <h1 className="text-lg font-bold text-gray-900">{title}</h1>}
          </div>
          {children}
        </div>
        <p className="text-[10px] text-gray-400 text-center mt-4">
          Powered by Quantix Technology
        </p>
      </div>
    </div>
  )
}

function PasswordField({ value, show, onChange, onToggle, placeholder }: {
  value: string; show: boolean
  onChange: (v: string) => void; onToggle: () => void
  placeholder: string
}) {
  return (
    <div className="flex items-center border border-gray-200 rounded-xl px-3 h-11 focus-within:border-gray-400 transition-colors mb-3">
      <Lock className="w-4 h-4 text-gray-400 shrink-0" />
      <input type={show ? "text" : "password"} placeholder={placeholder} value={value}
        onChange={e => onChange(e.target.value)}
        className="flex-1 text-sm outline-none bg-transparent ml-2.5" />
      <button type="button" onClick={onToggle} className="text-gray-400 hover:text-gray-600 ml-1">
        {show ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
      </button>
    </div>
  )
}

// Wrap in Suspense because useSearchParams() requires it in Next.js 13+
export default function ResetPasswordPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
      </div>
    }>
      <ResetPasswordInner />
    </Suspense>
  )
}
