"use client"

// Bulk Import Leads.
//
// Follows the pattern the rest of Laundry OS already uses for bulk data — drop
// zone, parse in the browser, preview before anything is written — so this
// reads as part of the same product rather than a second application.
//
// What it deliberately does NOT do is decide what is importable. The template
// is generated by the server from the tenant's active Lead Fields, and the
// server re-derives those same columns when the rows arrive. The browser only
// turns a file into rows.

import { useCallback, useRef, useState } from "react"
import * as XLSX from "xlsx"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Loader2, Upload, FileDown, AlertTriangle, CheckCircle2, X } from "lucide-react"
import { toast } from "sonner"
import { getAuthHeaders } from "@/lib/admin-fetch"

interface RowReport { row: number; status: "NEW" | "DUPLICATE" | "INVALID"; name: string; phone: string; reason?: string }
interface Counts { total: number; new: number; duplicate: number; invalid: number }

export function CrmLeadImportDialog({
  open, onClose, businessId, onImported,
}: { open: boolean; onClose: () => void; businessId: string; onImported: () => void }) {
  const [busy, setBusy] = useState(false)
  const [fileName, setFileName] = useState("")
  const [rows, setRows] = useState<Record<string, unknown>[]>([])
  const [counts, setCounts] = useState<Counts | null>(null)
  const [report, setReport] = useState<RowReport[]>([])
  const [ignored, setIgnored] = useState<string[]>([])
  const [done, setDone] = useState<{ imported: number; counts: Counts } | null>(null)
  const [dragging, setDragging] = useState(false)
  const fileInput = useRef<HTMLInputElement>(null)

  const reset = () => { setFileName(""); setRows([]); setCounts(null); setReport([]); setIgnored([]); setDone(null); if (fileInput.current) fileInput.current.value = "" }

  /**
   * Fetch the template, then hand the BYTES to the browser.
   *
   * window.open() cannot do this. A Laundry OS tenant user authenticates with
   * an Authorization: Bearer token held in localStorage, and a navigation the
   * browser performs itself carries no such header — so the route answered
   * "Not authenticated" to a perfectly valid session. The token stays out of
   * the URL, where it would end up in history, logs and referrers.
   *
   * The download itself is the pattern already used by Export on this screen:
   * an object URL on a real <a download>.
   */
  const downloadTemplate = async (format: "xlsx" | "csv") => {
    setBusy(true)
    try {
      const res = await fetch(
        `/api/laundry/crm/leads/template?businessId=${encodeURIComponent(businessId)}&format=${format}`,
        { headers: getAuthHeaders() },
      )
      if (!res.ok) {
        // The body is JSON on failure and a spreadsheet on success, so read it
        // only when something went wrong.
        const msg = await res.json().catch(() => null)
        throw new Error(msg?.error || `Could not build the template (HTTP ${res.status})`)
      }
      const blob = await res.blob()
      const a = document.createElement("a")
      a.href = URL.createObjectURL(blob)
      a.download = `lead-import-template.${format}`
      a.click()
      URL.revokeObjectURL(a.href)
      toast.success(`Template downloaded (.${format})`)
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not download the template")
    } finally { setBusy(false) }
  }

  const post = async (mode: "validate" | "commit", parsed: Record<string, unknown>[], name: string) => {
    const res = await fetch("/api/laundry/crm/leads/import", {
      method: "POST", headers: { "Content-Type": "application/json", ...getAuthHeaders() },
      body: JSON.stringify({ businessId, mode, rows: parsed, fileName: name }),
    })
    const json = await res.json()
    if (!res.ok || json.success === false) throw new Error(json.error || "Import failed")
    return json
  }

  const readFile = useCallback(async (file: File) => {
    if (!/\.(csv|xlsx|xls)$/i.test(file.name)) { toast.error("Choose a .csv, .xls or .xlsx file"); return }
    setBusy(true); setDone(null)
    try {
      const wb = XLSX.read(await file.arrayBuffer())
      // The Leads sheet when the template was used; otherwise the first sheet,
      // which is what a CSV has.
      const sheetName = wb.SheetNames.find((n) => n.trim().toLowerCase() === "leads") ?? wb.SheetNames[0]
      const parsed = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets[sheetName], { defval: "" })
      if (parsed.length === 0) { toast.error("That sheet has no rows"); return }

      const json = await post("validate", parsed, file.name)
      setFileName(file.name); setRows(parsed)
      setCounts(json.counts); setReport(json.report ?? []); setIgnored(json.ignored ?? [])
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "That file could not be read")
    } finally { setBusy(false) }
  }, [businessId])

  const commit = async () => {
    setBusy(true)
    try {
      const json = await post("commit", rows, fileName)
      setDone({ imported: json.imported, counts: json.counts })
      setReport(json.report ?? [])
      toast.success(`Imported ${json.imported} lead(s)`)
      onImported()
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Import failed")
    } finally { setBusy(false) }
  }

  /** Rejected rows, as a file — a list on screen is not something you can work from. */
  const downloadErrors = () => {
    const bad = report.filter((r) => r.status !== "NEW")
    const ws = XLSX.utils.aoa_to_sheet([
      ["Row", "Status", "Name", "Phone", "Reason"],
      ...bad.map((r) => [r.row, r.status, r.name, r.phone, r.reason ?? ""]),
    ])
    const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Errors")
    XLSX.writeFile(wb, "lead-import-errors.xlsx")
  }

  const badRows = report.filter((r) => r.status !== "NEW")

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o) { reset(); onClose() } }}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2"><Upload className="h-4 w-4" /> Bulk Import Leads</DialogTitle>
          <DialogDescription>
            The template is built from this business&rsquo;s active Lead Fields, in their configured order. Nothing is created until you confirm.
          </DialogDescription>
        </DialogHeader>

        {done ? (
          <div className="space-y-3">
            <div className="rounded-lg border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-800 flex items-start gap-2">
              <CheckCircle2 className="h-4 w-4 mt-0.5" />
              <div>
                Imported {done.imported} lead(s) from {done.counts.total} row(s).
                {done.counts.duplicate > 0 && <span className="block text-emerald-700/80">{done.counts.duplicate} already on file.</span>}
                {done.counts.invalid > 0 && <span className="block text-emerald-700/80">{done.counts.invalid} could not be imported.</span>}
              </div>
            </div>
            {badRows.length > 0 && (
              <Button variant="outline" className="w-full gap-2" onClick={downloadErrors}><FileDown className="h-4 w-4" /> Download Error Report</Button>
            )}
          </div>
        ) : !counts ? (
          <div className="space-y-3">
            <div
              onDragOver={(e) => { e.preventDefault(); setDragging(true) }}
              onDragLeave={() => setDragging(false)}
              onDrop={(e) => { e.preventDefault(); setDragging(false); const f = e.dataTransfer.files?.[0]; if (f) readFile(f) }}
              onClick={() => fileInput.current?.click()}
              className={`rounded-xl border-2 border-dashed p-8 text-center cursor-pointer transition-colors ${dragging ? "border-blue-500 bg-blue-50" : "border-slate-200 hover:border-slate-300 hover:bg-slate-50"}`}
            >
              {busy ? (
                <p className="text-sm text-slate-500 flex items-center justify-center gap-2"><Loader2 className="h-4 w-4 animate-spin" /> Checking…</p>
              ) : (
                <>
                  <Upload className="h-6 w-6 mx-auto text-slate-400" />
                  <p className="mt-2 text-sm font-medium text-slate-700">Upload CSV / Excel</p>
                  <p className="text-xs text-slate-500 mt-0.5">Drag &amp; drop your file here, or</p>
                  <span className="mt-2 inline-flex items-center h-9 px-4 rounded-lg border border-slate-300 bg-white text-sm font-medium">Choose File</span>
                  <p className="text-[11px] text-slate-400 mt-2">CSV, XLS, XLSX</p>
                </>
              )}
              <input ref={fileInput} type="file" accept=".csv,.xls,.xlsx" className="hidden"
                onChange={(e) => { const f = e.target.files?.[0]; if (f) readFile(f) }} />
            </div>
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1 gap-2 text-xs" onClick={() => downloadTemplate("xlsx")}><FileDown className="h-3.5 w-3.5" /> Download Template (.xlsx)</Button>
              <Button variant="outline" className="flex-1 gap-2 text-xs" onClick={() => downloadTemplate("csv")}><FileDown className="h-3.5 w-3.5" /> Download Template (.csv)</Button>
            </div>
          </div>
        ) : (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-sm font-medium truncate">{fileName}</p>
              <Button variant="ghost" size="sm" onClick={reset} className="gap-1 text-xs"><X className="h-3.5 w-3.5" /> Choose another</Button>
            </div>

            <div className="grid grid-cols-4 gap-2 text-center">
              {([["Total", counts.total, "text-slate-700"], ["New", counts.new, "text-emerald-700"], ["Duplicates", counts.duplicate, "text-amber-700"], ["Invalid", counts.invalid, "text-red-600"]] as const).map(([label, n, cls]) => (
                <div key={label} className="rounded-lg border p-2">
                  <p className={`text-lg font-bold ${cls}`}>{n}</p>
                  <p className="text-[11px] text-muted-foreground">{label}</p>
                </div>
              ))}
            </div>

            {ignored.length > 0 && (
              <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-[11px] text-amber-800">
                <p className="font-semibold flex items-center gap-1.5"><AlertTriangle className="h-3.5 w-3.5" /> Columns not read</p>
                <p className="mt-1">{ignored.join(", ")} — not an active Lead Field for this business, so {ignored.length === 1 ? "it was" : "they were"} ignored.</p>
              </div>
            )}

            <div className="rounded-lg border max-h-56 overflow-y-auto">
              <table className="w-full text-xs">
                <thead className="sticky top-0 bg-slate-50">
                  <tr><th className="text-left px-3 py-1.5 font-medium">Row</th><th className="text-left px-3 font-medium">Name</th><th className="text-left px-3 font-medium">Phone</th><th className="text-left px-3 font-medium">Status</th><th className="text-left px-3 font-medium">Reason</th></tr>
                </thead>
                <tbody>
                  {report.slice(0, 200).map((r) => (
                    <tr key={r.row} className="border-t">
                      <td className="px-3 py-1 text-slate-400">{r.row}</td>
                      <td className="px-3 truncate max-w-[140px]">{r.name || "—"}</td>
                      <td className="px-3">{r.phone || "—"}</td>
                      <td className="px-3">
                        <Badge variant="outline" className={`text-[10px] ${r.status === "NEW" ? "border-emerald-300 text-emerald-700" : r.status === "DUPLICATE" ? "border-amber-300 text-amber-700" : "border-red-300 text-red-600"}`}>{r.status}</Badge>
                      </td>
                      <td className="px-3 text-slate-500 truncate max-w-[200px]">{r.reason ?? ""}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="flex gap-2">
              <Button onClick={commit} disabled={busy || counts.new === 0} className="flex-1 gap-2 bg-blue-600 hover:bg-blue-700 text-white">
                {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />} Import {counts.new} Valid Lead{counts.new === 1 ? "" : "s"}
              </Button>
              {badRows.length > 0 && <Button variant="outline" className="gap-2" onClick={downloadErrors}><FileDown className="h-4 w-4" /> Errors</Button>}
            </div>
            {counts.new === 0 && <p className="text-[11px] text-center text-muted-foreground">Nothing new to import from this file.</p>}
          </div>
        )}

        <DialogFooter><Button variant="outline" onClick={() => { reset(); onClose() }}>Done</Button></DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
