"use client"

// ============================================================================
// Quantix Technology — Delivery Partner App Mock Data
// ============================================================================

export type DeliveryOrderStatus = "PICKUP" | "PICKED_UP" | "ON_THE_WAY" | "DELIVERED" | "CANCELLED"
export type NotificationType = "order" | "payment" | "system" | "promo"

export const partnerProfile = {
  id: "dp_1",
  name: "Ramesh K.",
  phone: "+91 91111 11111",
  email: "ramesh.k@quantix.dev",
  avatar: "",
  vehicleType: "Motorcycle",
  vehicleNumber: "MH-02-AB-1234",
  rating: 4.7,
  totalDeliveries: 458,
  isActive: true,
  bankAccount: "XXXX XXXX XXXX 4523",
  bankName: "HDFC Bank",
  upiId: "rameshk@upi",
  joinedDate: "2024-03-15",
  earnings: 156780,
}

export const assignedOrders = [
  {
    id: "del_ord_1",
    orderNumber: "FM-20250115-001",
    status: "PICKUP" as DeliveryOrderStatus,
    customerName: "Rajesh Kumar",
    customerPhone: "+91 98765 11111",
    deliveryAddress: "402, Lotus Apartments, Andheri West, Mumbai 400053",
    deliveryLat: 19.1364,
    deliveryLng: 72.8296,
    items: [
      { name: "Amul Toned Milk 1L", qty: 2 },
      { name: "Fresh Tomatoes 1kg", qty: 1 },
      { name: "Onion 1kg", qty: 2 },
      { name: "Maggi Noodles Pack of 4", qty: 3 },
    ],
    totalAmount: 396.64,
    paymentMethod: "UPI",
    storeName: "FreshMart Grocers",
    storeAddress: "Shop 12, Linking Road, Andheri West, Mumbai",
    pickupLat: 19.1197,
    pickupLng: 72.8464,
    estimatedDelivery: "25 min",
    deliveryOtp: "4829",
    distance: "3.2 km",
  },
  {
    id: "del_ord_2",
    orderNumber: "FM-20250115-002",
    status: "PICKED_UP" as DeliveryOrderStatus,
    customerName: "Sneha Patil",
    customerPhone: "+91 98765 22222",
    deliveryAddress: "B-12, Green Valley, Powai, Mumbai 400076",
    deliveryLat: 19.1177,
    deliveryLng: 72.9063,
    items: [
      { name: "Basmati Rice Premium 5kg", qty: 1 },
      { name: "MDH Garam Masala 100g", qty: 2 },
      { name: "Surf Excel Matic 1kg", qty: 1 },
    ],
    totalAmount: 1421.20,
    paymentMethod: "CARD",
    storeName: "FreshMart Grocers",
    storeAddress: "Shop 12, Linking Road, Andheri West, Mumbai",
    pickupLat: 19.1197,
    pickupLng: 72.8464,
    estimatedDelivery: "15 min",
    deliveryOtp: "7316",
    distance: "4.5 km",
  },
  {
    id: "del_ord_3",
    orderNumber: "FM-20250115-003",
    status: "ON_THE_WAY" as DeliveryOrderStatus,
    customerName: "Anand Joshi",
    customerPhone: "+91 98765 33333",
    deliveryAddress: "701, Skyline Tower, Juhu, Mumbai 400049",
    deliveryLat: 19.0968,
    deliveryLng: 72.8267,
    items: [
      { name: "Amul Butter 500g", qty: 1 },
      { name: "Britannia Bread 400g", qty: 2 },
      { name: "Coca Cola 2L", qty: 2 },
    ],
    totalAmount: 583.12,
    paymentMethod: "UPI",
    storeName: "FreshMart Grocers",
    storeAddress: "Shop 12, Linking Road, Andheri West, Mumbai",
    pickupLat: 19.1197,
    pickupLng: 72.8464,
    estimatedDelivery: "8 min",
    deliveryOtp: "2054",
    distance: "2.8 km",
  },
  {
    id: "del_ord_4",
    orderNumber: "FM-20250115-005",
    status: "DELIVERED" as DeliveryOrderStatus,
    customerName: "Mohan Sharma",
    customerPhone: "+91 98765 55555",
    deliveryAddress: "23, Hill View Road, Bandra West, Mumbai 400050",
    deliveryLat: 19.0596,
    deliveryLng: 72.8295,
    items: [
      { name: "Green Capsicum 500g", qty: 2 },
      { name: "Frozen Peas 500g", qty: 1 },
      { name: "Dove Shampoo 180ml", qty: 1 },
      { name: "Amul Toned Milk 500ml", qty: 3 },
    ],
    totalAmount: 454.48,
    paymentMethod: "UPI",
    storeName: "FreshMart Grocers",
    storeAddress: "Shop 12, Linking Road, Andheri West, Mumbai",
    pickupLat: 19.1197,
    pickupLng: 72.8464,
    estimatedDelivery: "Delivered",
    deliveryOtp: "9187",
    distance: "5.1 km",
  },
]

export const earningsData = {
  todayEarnings: 847,
  weeklyEarnings: 5420,
  monthlyEarnings: 18750,
  todayDeliveries: 7,
  weeklyDeliveries: 38,
  monthlyDeliveries: 142,
  averagePerDelivery: 42,
  dailyBreakdown: [
    { date: "Mon", deliveries: 5, earnings: 620 },
    { date: "Tue", deliveries: 8, earnings: 890 },
    { date: "Wed", deliveries: 6, earnings: 710 },
    { date: "Thu", deliveries: 7, earnings: 847 },
    { date: "Fri", deliveries: 4, earnings: 480 },
    { date: "Sat", deliveries: 5, earnings: 580 },
    { date: "Sun", deliveries: 3, earnings: 350 },
  ],
  weeklyBreakdown: [
    { date: "Week 1", deliveries: 32, earnings: 4100 },
    { date: "Week 2", deliveries: 38, earnings: 5420 },
    { date: "Week 3", deliveries: 35, earnings: 4800 },
    { date: "Week 4", deliveries: 37, earnings: 4430 },
  ],
}

export const notifications = [
  { id: "n_1", type: "order" as NotificationType, title: "New Order Assigned", message: "Order FM-20250115-006 has been assigned to you", time: "2 min ago", read: false },
  { id: "n_2", type: "payment" as NotificationType, title: "Payment Received", message: "₹42.00 delivery fee credited for order FM-20250115-004", time: "15 min ago", read: false },
  { id: "n_3", type: "system" as NotificationType, title: "Schedule Update", message: "Your shift has been confirmed for tomorrow 8AM - 4PM", time: "1 hr ago", read: true },
  { id: "n_4", type: "promo" as NotificationType, title: "Bonus Alert!", message: "Complete 5 more deliveries today to earn ₹100 bonus", time: "2 hrs ago", read: true },
  { id: "n_5", type: "order" as NotificationType, title: "Delivery Confirmed", message: "Order FM-20250115-004 delivered successfully", time: "3 hrs ago", read: true },
  { id: "n_6", type: "system" as NotificationType, title: "App Update", message: "New version available with improved navigation", time: "5 hrs ago", read: true },
]
