// Processing Package(s) for an order — the operational QR AFTER Store Audit.
// GET  — list this order's packages.
// POST — generate packages (one per pickup bag, else one per order). Honours the
//        tenant setting processingPackageQrMode: GENERATE_NEW (new PKG QR) or
//        REUSE_BAG (keep the Pickup Bag QR). Idempotent. No invoice change —
//        invoice is still generated by the existing engine after audit.
import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { requireLaundryPermission } from "@/lib/laundry-rbac"
import { generateProcessingPackageCode } from "@/lib/laundry-codes"

export const runtime = "nodejs"

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params
    const order = await prisma.laundryOrder.findUnique({ where: { id }, select: { businessId: true } })
    if (!order) return NextResponse.json({ error: "Order not found" }, { status: 404 })
    const guard = await requireLaundryPermission(request, order.businessId, "laundry.orders.view")
    if (!guard.ok) return guard.res
    const packages = await prisma.laundryProcessingPackage.findMany({ where: { orderId: id }, orderBy: { createdAt: "asc" } })
    return NextResponse.json({ success: true, data: packages })
  } catch (e) {
    console.error("[processing-package] GET", e)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params
    const order = await prisma.laundryOrder.findUnique({ where: { id }, select: { id: true, businessId: true, orderNumber: true, _count: { select: { items: true } } } })
    if (!order) return NextResponse.json({ error: "Order not found" }, { status: 404 })
    const guard = await requireLaundryPermission(request, order.businessId, "laundry.orders.create")
    if (!guard.ok) return guard.res

    const existing = await prisma.laundryProcessingPackage.findMany({ where: { orderId: id }, orderBy: { createdAt: "asc" } })
    if (existing.length > 0) return NextResponse.json({ success: true, data: existing, alreadyGenerated: true })

    const biz = await prisma.laundryBusiness.findUnique({ where: { id: order.businessId }, select: { processingPackageQrMode: true } })
    const reuse = biz?.processingPackageQrMode === "REUSE_BAG"
    const bags = await prisma.laundryPickupBag.findMany({ where: { orderId: id }, orderBy: { createdAt: "asc" } })
    const garmentCount = order._count.items

    const created: Awaited<ReturnType<typeof prisma.laundryProcessingPackage.create>>[] = []
    // One package per pickup bag (parent→child). If no bags (walk-in/garment),
    // one package for the order.
    const sources = bags.length ? bags.map((b) => ({ pickupBagId: b.id, serviceId: b.serviceId, serviceName: b.serviceName, bagCode: b.code, bagQr: b.qrValue })) : [{ pickupBagId: null, serviceId: null, serviceName: null as string | null, bagCode: null as string | null, bagQr: null as string | null }]
    for (const s of sources) {
      const code = reuse && s.bagCode ? s.bagCode : await generateProcessingPackageCode()
      const qrValue = reuse && s.bagQr ? s.bagQr : code
      const pkg = await prisma.laundryProcessingPackage.create({
        data: {
          code, qrValue, businessId: order.businessId, orderId: order.id, orderNumber: order.orderNumber,
          pickupBagId: s.pickupBagId, serviceId: s.serviceId, serviceName: s.serviceName,
          garmentCount, weightKg: 0, reusedBagQr: reuse && !!s.bagCode, status: "CREATED",
        },
      })
      if (s.pickupBagId) await prisma.laundryPickupBag.update({ where: { id: s.pickupBagId }, data: { status: "AUDITED", auditedAt: new Date() } }).catch(() => {})
      created.push(pkg)
    }
    return NextResponse.json({ success: true, data: created, mode: reuse ? "REUSE_BAG" : "GENERATE_NEW" }, { status: 201 })
  } catch (e) {
    console.error("[processing-package] POST", e)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
