// ============================================================================
// Quantix Core — Notification Center Mock Data
// Realistic notification templates for each event type and channel
// ============================================================================

export type NotificationEventType = "ORDER_STATUS" | "DELIVERY_UPDATE" | "PROMOTION" | "SUBSCRIPTION" | "PAYMENT" | "SYSTEM";
export type NotificationChannel = "PUSH" | "EMAIL" | "WHATSAPP" | "IN_APP";

export interface NotificationItem {
  id: string;
  type: NotificationEventType;
  channel: NotificationChannel;
  title: string;
  message: string;
  recipientName: string;
  recipientId: string;
  isRead: boolean;
  isActionable: boolean;
  actionLabel?: string;
  actionUrl?: string;
  priority: "LOW" | "NORMAL" | "HIGH";
  createdAt: string;
  metadata: Record<string, unknown>;
}

export interface NotificationPreference {
  eventType: NotificationEventType;
  channel: NotificationChannel;
  enabled: boolean;
}

export const eventTypeConfig: Record<NotificationEventType, { label: string; color: string; bgColor: string; icon: string }> = {
  ORDER_STATUS: { label: "Order Status", color: "text-emerald-700", bgColor: "bg-emerald-100", icon: "📦" },
  DELIVERY_UPDATE: { label: "Delivery Update", color: "text-sky-700", bgColor: "bg-sky-100", icon: "🚚" },
  PROMOTION: { label: "Promotion", color: "text-amber-700", bgColor: "bg-amber-100", icon: "🎉" },
  SUBSCRIPTION: { label: "Subscription", color: "text-violet-700", bgColor: "bg-violet-100", icon: "🔄" },
  PAYMENT: { label: "Payment", color: "text-emerald-700", bgColor: "bg-emerald-100", icon: "💰" },
  SYSTEM: { label: "System", color: "text-slate-700", bgColor: "bg-slate-100", icon: "⚙️" },
};

export const channelConfig: Record<NotificationChannel, { label: string; color: string; bgColor: string }> = {
  PUSH: { label: "Push", color: "text-violet-600", bgColor: "bg-violet-50" },
  EMAIL: { label: "Email", color: "text-sky-600", bgColor: "bg-sky-50" },
  WHATSAPP: { label: "WhatsApp", color: "text-emerald-600", bgColor: "bg-emerald-50" },
  IN_APP: { label: "In-App", color: "text-amber-600", bgColor: "bg-amber-50" },
};

// ============================================================================
// Default notification preferences
// ============================================================================

export const defaultPreferences: NotificationPreference[] = [
  { eventType: "ORDER_STATUS", channel: "PUSH", enabled: true },
  { eventType: "ORDER_STATUS", channel: "EMAIL", enabled: true },
  { eventType: "ORDER_STATUS", channel: "WHATSAPP", enabled: false },
  { eventType: "ORDER_STATUS", channel: "IN_APP", enabled: true },
  { eventType: "DELIVERY_UPDATE", channel: "PUSH", enabled: true },
  { eventType: "DELIVERY_UPDATE", channel: "EMAIL", enabled: false },
  { eventType: "DELIVERY_UPDATE", channel: "WHATSAPP", enabled: true },
  { eventType: "DELIVERY_UPDATE", channel: "IN_APP", enabled: true },
  { eventType: "PROMOTION", channel: "PUSH", enabled: true },
  { eventType: "PROMOTION", channel: "EMAIL", enabled: true },
  { eventType: "PROMOTION", channel: "WHATSAPP", enabled: false },
  { eventType: "PROMOTION", channel: "IN_APP", enabled: true },
  { eventType: "SUBSCRIPTION", channel: "PUSH", enabled: true },
  { eventType: "SUBSCRIPTION", channel: "EMAIL", enabled: true },
  { eventType: "SUBSCRIPTION", channel: "WHATSAPP", enabled: true },
  { eventType: "SUBSCRIPTION", channel: "IN_APP", enabled: true },
  { eventType: "PAYMENT", channel: "PUSH", enabled: true },
  { eventType: "PAYMENT", channel: "EMAIL", enabled: true },
  { eventType: "PAYMENT", channel: "WHATSAPP", enabled: false },
  { eventType: "PAYMENT", channel: "IN_APP", enabled: true },
  { eventType: "SYSTEM", channel: "PUSH", enabled: true },
  { eventType: "SYSTEM", channel: "EMAIL", enabled: true },
  { eventType: "SYSTEM", channel: "WHATSAPP", enabled: false },
  { eventType: "SYSTEM", channel: "IN_APP", enabled: true },
];

// ============================================================================
// Mock notifications — 20 realistic entries
// ============================================================================

export const notificationItems: NotificationItem[] = [
  {
    id: "notif_201",
    type: "ORDER_STATUS",
    channel: "PUSH",
    title: "New order received!",
    message: "Order FM-20250115-007 from Rajesh Kumar — 4 items, ₹454.48. Confirm within 5 minutes.",
    recipientName: "FreshMart Grocers",
    recipientId: "biz_001",
    isRead: false,
    isActionable: true,
    actionLabel: "View Order",
    actionUrl: "/orders/FM-20250115-007",
    priority: "HIGH",
    createdAt: "2025-01-15T14:30:00Z",
    metadata: { orderId: "ord_893", orderNumber: "FM-20250115-007", totalAmount: 454.48 },
  },
  {
    id: "notif_202",
    type: "DELIVERY_UPDATE",
    channel: "WHATSAPP",
    title: "Delivery partner assigned",
    message: "Ramesh K. has been assigned for order FM-20250115-005. ETA: 25 minutes.",
    recipientName: "Mohan Sharma",
    recipientId: "cust_005",
    isRead: false,
    isActionable: true,
    actionLabel: "Track Order",
    actionUrl: "/track/FM-20250115-005",
    priority: "NORMAL",
    createdAt: "2025-01-15T14:15:00Z",
    metadata: { orderId: "ord_891", partnerName: "Ramesh K.", eta: 25 },
  },
  {
    id: "notif_203",
    type: "PAYMENT",
    channel: "EMAIL",
    title: "Payment of ₹4,999 received",
    message: "Monthly subscription payment processed successfully via UPI. Next billing date: Feb 15, 2025.",
    recipientName: "FreshMart Grocers",
    recipientId: "biz_001",
    isRead: false,
    isActionable: false,
    priority: "NORMAL",
    createdAt: "2025-01-15T12:00:00Z",
    metadata: { amount: 4999, method: "UPI", nextBillingDate: "2025-02-15" },
  },
  {
    id: "notif_204",
    type: "ORDER_STATUS",
    channel: "IN_APP",
    title: "Order confirmed",
    message: "Your order FM-20250115-003 has been confirmed and is being prepared. Expected delivery in 30 min.",
    recipientName: "Anand Joshi",
    recipientId: "cust_003",
    isRead: true,
    isActionable: false,
    priority: "NORMAL",
    createdAt: "2025-01-15T11:50:00Z",
    metadata: { orderId: "ord_889", status: "CONFIRMED", eta: 30 },
  },
  {
    id: "notif_205",
    type: "PROMOTION",
    channel: "PUSH",
    title: "🎉 Weekend Special — 20% off!",
    message: "Get 20% off on all fresh vegetables this weekend at FreshMart. Use code: FRESH20",
    recipientName: "All Customers",
    recipientId: "all",
    isRead: false,
    isActionable: true,
    actionLabel: "Shop Now",
    actionUrl: "/offers/FRESH20",
    priority: "NORMAL",
    createdAt: "2025-01-15T10:00:00Z",
    metadata: { promoCode: "FRESH20", discount: 20, validUntil: "2025-01-19" },
  },
  {
    id: "notif_206",
    type: "SUBSCRIPTION",
    channel: "WHATSAPP",
    title: "Subscription expiring in 3 days",
    message: "Hi Sneha! Your monthly grocery subscription expires on Jan 18. Renew now to continue getting free delivery.",
    recipientName: "Sneha Patil",
    recipientId: "cust_002",
    isRead: false,
    isActionable: true,
    actionLabel: "Renew Now",
    actionUrl: "/subscriptions/renew",
    priority: "HIGH",
    createdAt: "2025-01-15T09:00:00Z",
    metadata: { subscriptionId: "sub_045", expiresOn: "2025-01-18", plan: "Monthly Grocery Box" },
  },
  {
    id: "notif_207",
    type: "DELIVERY_UPDATE",
    channel: "PUSH",
    title: "Order delivered!",
    message: "Your order FM-20250115-006 has been delivered. Rate your experience!",
    recipientName: "Kavita Reddy",
    recipientId: "cust_006",
    isRead: true,
    isActionable: true,
    actionLabel: "Rate Order",
    actionUrl: "/rate/FM-20250115-006",
    priority: "LOW",
    createdAt: "2025-01-15T08:30:00Z",
    metadata: { orderId: "ord_892", deliveredAt: "2025-01-15T08:30:00Z" },
  },
  {
    id: "notif_208",
    type: "SYSTEM",
    channel: "IN_APP",
    title: "Scheduled maintenance tonight",
    message: "Platform maintenance scheduled from 2:00 AM to 4:00 AM IST. Services may be briefly unavailable.",
    recipientName: "All Businesses",
    recipientId: "all",
    isRead: false,
    isActionable: false,
    priority: "HIGH",
    createdAt: "2025-01-14T18:00:00Z",
    metadata: { maintenanceWindow: "2:00 AM - 4:00 AM IST", date: "2025-01-16" },
  },
  {
    id: "notif_209",
    type: "PAYMENT",
    channel: "EMAIL",
    title: "Refund of ₹491.12 processed",
    message: "Refund for cancelled order FM-20250114-007 has been processed. Amount will reflect in 3-5 business days.",
    recipientName: "Deepa Nair",
    recipientId: "cust_004",
    isRead: true,
    isActionable: false,
    priority: "NORMAL",
    createdAt: "2025-01-14T16:45:00Z",
    metadata: { refundAmount: 491.12, orderId: "ord_887", method: "UPI" },
  },
  {
    id: "notif_210",
    type: "ORDER_STATUS",
    channel: "WHATSAPP",
    title: "Order out for delivery",
    message: "Your FreshMart order is on its way! Delivery partner: Suresh M. OTP for delivery: 4829",
    recipientName: "Anand Joshi",
    recipientId: "cust_003",
    isRead: false,
    isActionable: true,
    actionLabel: "Track",
    actionUrl: "/track/FM-20250115-003",
    priority: "NORMAL",
    createdAt: "2025-01-14T15:30:00Z",
    metadata: { orderId: "ord_889", partnerName: "Suresh M.", otp: "4829" },
  },
  {
    id: "notif_211",
    type: "PROMOTION",
    channel: "EMAIL",
    title: "Introducing: Monthly Grocery Box 📦",
    message: "Subscribe to our new Monthly Grocery Box and save 15% on essentials. Free delivery included!",
    recipientName: "Rajesh Kumar",
    recipientId: "cust_001",
    isRead: true,
    isActionable: true,
    actionLabel: "Subscribe",
    actionUrl: "/subscriptions/grocery-box",
    priority: "LOW",
    createdAt: "2025-01-14T12:00:00Z",
    metadata: { planId: "subplan_grocery_box", discount: 15 },
  },
  {
    id: "notif_212",
    type: "SYSTEM",
    channel: "PUSH",
    title: "New feature: Advanced Reports",
    message: "Advanced analytics dashboard is now available for your business. View sales trends, customer insights, and more!",
    recipientName: "FreshMart Grocers",
    recipientId: "biz_001",
    isRead: false,
    isActionable: true,
    actionLabel: "View Reports",
    actionUrl: "/reports/advanced",
    priority: "NORMAL",
    createdAt: "2025-01-14T10:00:00Z",
    metadata: { feature: "advanced_reports" },
  },
  {
    id: "notif_213",
    type: "SUBSCRIPTION",
    channel: "EMAIL",
    title: "Subscription renewed successfully",
    message: "Your Pro plan has been renewed for ₹49,999. Valid until Jan 14, 2026.",
    recipientName: "QuickBite Restaurants",
    recipientId: "biz_008",
    isRead: true,
    isActionable: false,
    priority: "NORMAL",
    createdAt: "2025-01-13T09:00:00Z",
    metadata: { planPrice: 49999, billingCycle: "YEARLY", validUntil: "2026-01-14" },
  },
  {
    id: "notif_214",
    type: "PAYMENT",
    channel: "WHATSAPP",
    title: "UPI payment of ₹1,421.20 received",
    message: "Payment received from Sneha Patil for order FM-20250115-002 via UPI. Transaction ID: pay_187UPI",
    recipientName: "FreshMart Grocers",
    recipientId: "biz_001",
    isRead: false,
    isActionable: false,
    priority: "NORMAL",
    createdAt: "2025-01-13T08:30:00Z",
    metadata: { amount: 1421.20, method: "UPI", orderId: "ord_888" },
  },
  {
    id: "notif_215",
    type: "DELIVERY_UPDATE",
    channel: "IN_APP",
    title: "Delivery delayed by 10 min",
    message: "Due to traffic, order FM-20250115-005 delivery is delayed. New ETA: 35 minutes.",
    recipientName: "Mohan Sharma",
    recipientId: "cust_005",
    isRead: false,
    isActionable: true,
    actionLabel: "Track",
    actionUrl: "/track/FM-20250115-005",
    priority: "HIGH",
    createdAt: "2025-01-12T18:45:00Z",
    metadata: { orderId: "ord_891", originalEta: 25, newEta: 35, reason: "traffic" },
  },
  {
    id: "notif_216",
    type: "ORDER_STATUS",
    channel: "EMAIL",
    title: "Order cancelled",
    message: "Order FM-20250114-007 has been cancelled by the customer. Refund of ₹491.12 will be processed.",
    recipientName: "FreshMart Grocers",
    recipientId: "biz_001",
    isRead: true,
    isActionable: false,
    priority: "NORMAL",
    createdAt: "2025-01-12T16:30:00Z",
    metadata: { orderId: "ord_887", cancelReason: "Customer requested", refundAmount: 491.12 },
  },
  {
    id: "notif_217",
    type: "PROMOTION",
    channel: "WHATSAPP",
    title: "Flash Sale — 30% off snacks! 🍿",
    message: "Limited time offer: 30% off on all snacks and chips. Valid today only! Code: SNACK30",
    recipientName: "All Customers",
    recipientId: "all",
    isRead: false,
    isActionable: true,
    actionLabel: "Shop Now",
    actionUrl: "/offers/SNACK30",
    priority: "NORMAL",
    createdAt: "2025-01-12T10:00:00Z",
    metadata: { promoCode: "SNACK30", discount: 30, validUntil: "2025-01-12T23:59:00Z" },
  },
  {
    id: "notif_218",
    type: "SYSTEM",
    channel: "EMAIL",
    title: "Weekly performance digest",
    message: "Your weekly platform digest is ready. Revenue is up 12% compared to last week. 156 orders processed.",
    recipientName: "FreshMart Grocers",
    recipientId: "biz_001",
    isRead: true,
    isActionable: true,
    actionLabel: "View Dashboard",
    actionUrl: "/dashboard",
    priority: "LOW",
    createdAt: "2025-01-11T08:00:00Z",
    metadata: { revenueChange: 12, orderCount: 156 },
  },
  {
    id: "notif_219",
    type: "SUBSCRIPTION",
    channel: "PUSH",
    title: "Loyalty points expiring",
    message: "You have 1,420 loyalty points expiring on Jan 31. Redeem them before they expire!",
    recipientName: "Rajesh Kumar",
    recipientId: "cust_001",
    isRead: false,
    isActionable: true,
    actionLabel: "Redeem Points",
    actionUrl: "/loyalty/redeem",
    priority: "NORMAL",
    createdAt: "2025-01-10T12:00:00Z",
    metadata: { points: 1420, expiresOn: "2025-01-31" },
  },
  {
    id: "notif_220",
    type: "PAYMENT",
    channel: "IN_APP",
    title: "Payment overdue",
    message: "Your subscription payment of ₹4,999 is overdue by 5 days. Please pay to avoid service interruption.",
    recipientName: "HomeEssentials Mart",
    recipientId: "biz_025",
    isRead: false,
    isActionable: true,
    actionLabel: "Pay Now",
    actionUrl: "/billing/pay",
    priority: "HIGH",
    createdAt: "2025-01-10T09:00:00Z",
    metadata: { amount: 4999, overdueDays: 5, businessId: "biz_025" },
  },
];
