// ============================================================================
// Quantix Core — Audit Log Mock Data
// Realistic audit log entries for the admin audit viewer
// ============================================================================

export interface AuditLogEntry {
  id: string;
  userId: string;
  userName: string;
  action: string;
  entityType: string;
  entityId: string;
  details: string;
  ipAddress: string;
  metadata: Record<string, unknown>;
  createdAt: string;
}

export interface ActionTypeConfig {
  value: string;
  label: string;
  color: string;
  bgColor: string;
}

export interface EntityTypeConfig {
  value: string;
  label: string;
}

// ============================================================================
// Action Types — color-coded for visual identification
// ============================================================================

export const actionTypes: ActionTypeConfig[] = [
  { value: "CREATE", label: "Create", color: "text-emerald-700", bgColor: "bg-emerald-100" },
  { value: "UPDATE", label: "Update", color: "text-sky-700", bgColor: "bg-sky-100" },
  { value: "DELETE", label: "Delete", color: "text-red-700", bgColor: "bg-red-100" },
  { value: "LOGIN", label: "Login", color: "text-purple-700", bgColor: "bg-purple-100" },
  { value: "LOGOUT", label: "Logout", color: "text-slate-600", bgColor: "bg-slate-100" },
  { value: "EXPORT", label: "Export", color: "text-amber-700", bgColor: "bg-amber-100" },
  { value: "PAYMENT", label: "Payment", color: "text-emerald-700", bgColor: "bg-emerald-100" },
  { value: "REFUND", label: "Refund", color: "text-orange-700", bgColor: "bg-orange-100" },
  { value: "STATUS_CHANGE", label: "Status Change", color: "text-violet-700", bgColor: "bg-violet-100" },
  { value: "CONFIG", label: "Config Change", color: "text-cyan-700", bgColor: "bg-cyan-100" },
];

// ============================================================================
// Entity Types
// ============================================================================

export const entityTypes: EntityTypeConfig[] = [
  { value: "Business", label: "Business" },
  { value: "Store", label: "Store" },
  { value: "Order", label: "Order" },
  { value: "Product", label: "Product" },
  { value: "Customer", label: "Customer" },
  { value: "User", label: "User" },
  { value: "Subscription", label: "Subscription" },
  { value: "Payment", label: "Payment" },
  { value: "Lead", label: "Lead" },
  { value: "Invoice", label: "Invoice" },
  { value: "Domain", label: "Domain" },
  { value: "Deployment", label: "Deployment" },
  { value: "Session", label: "POS Session" },
];

// ============================================================================
// Mock Audit Logs — 30 realistic entries
// ============================================================================

export const auditLogs: AuditLogEntry[] = [
  {
    id: "log_001",
    userId: "usr_001",
    userName: "Priya Sharma",
    action: "CREATE",
    entityType: "Lead",
    entityId: "lead_042",
    details: "New lead created from Meta Ads — SpiceMart Groceries, contact: Ravi Mehta",
    ipAddress: "192.168.1.105",
    metadata: { source: "META_ADS", businessType: "GROCERY", estimatedValue: 4999 },
    createdAt: "2025-01-15T14:32:00Z",
  },
  {
    id: "log_002",
    userId: "usr_002",
    userName: "Rahul Verma",
    action: "UPDATE",
    entityType: "Lead",
    entityId: "lead_038",
    details: "Lead stage changed from DEMO_SHARED to NEGOTIATION for QuickBite Restaurants",
    ipAddress: "192.168.1.112",
    metadata: { previousStage: "DEMO_SHARED", newStage: "NEGOTIATION" },
    createdAt: "2025-01-15T13:45:00Z",
  },
  {
    id: "log_003",
    userId: "usr_003",
    userName: "Admin System",
    action: "PAYMENT",
    entityType: "Payment",
    entityId: "pay_189",
    details: "Monthly subscription payment of ₹4,999 received from FreshMart Grocers via Razorpay",
    ipAddress: "10.0.0.1",
    metadata: { amount: 4999, method: "UPI", gateway: "razorpay", transactionId: "rp_9f8e7d6c" },
    createdAt: "2025-01-15T12:15:00Z",
  },
  {
    id: "log_004",
    userId: "usr_001",
    userName: "Priya Sharma",
    action: "CREATE",
    entityType: "Business",
    entityId: "biz_028",
    details: "Business 'MedQuick Pharmacy' created after payment verification. Deployed to production.",
    ipAddress: "192.168.1.105",
    metadata: { businessType: "PHARMACY", planId: "plan_monthly", billingCycle: "MONTHLY" },
    createdAt: "2025-01-15T11:30:00Z",
  },
  {
    id: "log_005",
    userId: "usr_004",
    userName: "Amit Patel",
    action: "LOGIN",
    entityType: "User",
    entityId: "usr_004",
    details: "User logged in via email OTP from Mumbai",
    ipAddress: "103.212.88.42",
    metadata: { authProvider: "EMAIL_OTP", device: "Chrome/Windows" },
    createdAt: "2025-01-15T10:05:00Z",
  },
  {
    id: "log_006",
    userId: "usr_005",
    userName: "Sneha Iyer",
    action: "STATUS_CHANGE",
    entityType: "Order",
    entityId: "ord_892",
    details: "Order FM-20250115-003 status changed from PREPARING to OUT_FOR_DELIVERY",
    ipAddress: "192.168.1.108",
    metadata: { previousStatus: "PREPARING", newStatus: "OUT_FOR_DELIVERY", assignedTo: "dp_001" },
    createdAt: "2025-01-15T09:50:00Z",
  },
  {
    id: "log_007",
    userId: "usr_003",
    userName: "Admin System",
    action: "CREATE",
    entityType: "Deployment",
    entityId: "deploy_045",
    details: "Deployment completed for BookNest Library — website live at booknest.quantixtechnology.in",
    ipAddress: "10.0.0.1",
    metadata: { type: "WEBSITE", environment: "production", status: "LIVE" },
    createdAt: "2025-01-15T08:30:00Z",
  },
  {
    id: "log_008",
    userId: "usr_002",
    userName: "Rahul Verma",
    action: "UPDATE",
    entityType: "Business",
    entityId: "biz_015",
    details: "Updated primary color and logo for UrbanBrew Coffee",
    ipAddress: "192.168.1.112",
    metadata: { previousColor: "#3B82F6", newColor: "#92400E", logoUpdated: true },
    createdAt: "2025-01-15T07:45:00Z",
  },
  {
    id: "log_009",
    userId: "usr_006",
    userName: "Vikram Singh",
    action: "DELETE",
    entityType: "Product",
    entityId: "prod_234",
    details: "Product 'Expired Coffee Beans 250g' removed from FreshMart catalog",
    ipAddress: "192.168.1.120",
    metadata: { productName: "Expired Coffee Beans 250g", reason: "discontinued" },
    createdAt: "2025-01-14T18:20:00Z",
  },
  {
    id: "log_010",
    userId: "usr_005",
    userName: "Sneha Iyer",
    action: "REFUND",
    entityType: "Payment",
    entityId: "pay_185",
    details: "Refund of ₹491.12 processed for order FM-20250114-007 (Deepa Nair — cancelled order)",
    ipAddress: "192.168.1.108",
    metadata: { refundAmount: 491.12, reason: "Order cancelled by customer", orderId: "ord_887" },
    createdAt: "2025-01-14T16:45:00Z",
  },
  {
    id: "log_011",
    userId: "usr_001",
    userName: "Priya Sharma",
    action: "EXPORT",
    entityType: "Order",
    entityId: "batch_012",
    details: "Exported 156 orders as CSV for FreshMart Grocers — date range Jan 1-14, 2025",
    ipAddress: "192.168.1.105",
    metadata: { format: "CSV", recordCount: 156, dateFrom: "2025-01-01", dateTo: "2025-01-14" },
    createdAt: "2025-01-14T15:30:00Z",
  },
  {
    id: "log_012",
    userId: "usr_004",
    userName: "Amit Patel",
    action: "CONFIG",
    entityType: "Store",
    entityId: "store_008",
    details: "Updated delivery radius from 3km to 5km for FreshMart - Andheri store",
    ipAddress: "103.212.88.42",
    metadata: { previousRadius: 3, newRadius: 5, storeName: "FreshMart - Andheri" },
    createdAt: "2025-01-14T14:10:00Z",
  },
  {
    id: "log_013",
    userId: "usr_003",
    userName: "Admin System",
    action: "PAYMENT",
    entityType: "Payment",
    entityId: "pay_187",
    details: "Yearly subscription payment of ₹49,999 received from QuickBite Restaurants",
    ipAddress: "10.0.0.1",
    metadata: { amount: 49999, method: "NETBANKING", gateway: "razorpay" },
    createdAt: "2025-01-14T12:00:00Z",
  },
  {
    id: "log_014",
    userId: "usr_002",
    userName: "Rahul Verma",
    action: "CREATE",
    entityType: "Customer",
    entityId: "cust_456",
    details: "New customer Kavita Reddy registered via customer app for FreshMart Grocers",
    ipAddress: "192.168.1.112",
    metadata: { customerPhone: "+91 98765 66666", tier: "BRONZE" },
    createdAt: "2025-01-14T10:20:00Z",
  },
  {
    id: "log_015",
    userId: "usr_006",
    userName: "Vikram Singh",
    action: "UPDATE",
    entityType: "Product",
    entityId: "prod_045",
    details: "Price updated for Amul Toned Milk 1L — MRP ₹56, selling price ₹52 → ₹54",
    ipAddress: "192.168.1.120",
    metadata: { previousPrice: 52, newPrice: 54, mrp: 56 },
    createdAt: "2025-01-14T09:00:00Z",
  },
  {
    id: "log_016",
    userId: "usr_001",
    userName: "Priya Sharma",
    action: "STATUS_CHANGE",
    entityType: "Lead",
    entityId: "lead_040",
    details: "Lead stage changed from NEGOTIATION to PAYMENT_PENDING for StyleHub Fashion",
    ipAddress: "192.168.1.105",
    metadata: { previousStage: "NEGOTIATION", newStage: "PAYMENT_PENDING" },
    createdAt: "2025-01-13T17:30:00Z",
  },
  {
    id: "log_017",
    userId: "usr_004",
    userName: "Amit Patel",
    action: "LOGIN",
    entityType: "User",
    entityId: "usr_004",
    details: "User logged in via WhatsApp OTP from Delhi",
    ipAddress: "49.207.55.88",
    metadata: { authProvider: "WHATSAPP_OTP", device: "Chrome/MacOS" },
    createdAt: "2025-01-13T16:00:00Z",
  },
  {
    id: "log_018",
    userId: "usr_005",
    userName: "Sneha Iyer",
    action: "CREATE",
    entityType: "Order",
    entityId: "ord_888",
    details: "New POS order FM-20250113-012 created — ₹517.00, cash payment, walk-in customer",
    ipAddress: "192.168.1.108",
    metadata: { orderType: "POS", totalAmount: 517, paymentMethod: "CASH" },
    createdAt: "2025-01-13T14:10:00Z",
  },
  {
    id: "log_019",
    userId: "usr_003",
    userName: "Admin System",
    action: "CONFIG",
    entityType: "Business",
    entityId: "biz_015",
    details: "Feature flag 'hasAdvancedReports' enabled for UrbanBrew Coffee",
    ipAddress: "10.0.0.1",
    metadata: { feature: "hasAdvancedReports", enabled: true },
    createdAt: "2025-01-13T11:00:00Z",
  },
  {
    id: "log_020",
    userId: "usr_002",
    userName: "Rahul Verma",
    action: "DELETE",
    entityType: "Domain",
    entityId: "domain_023",
    details: "Staging domain staging.booknest.in removed for BookNest Library",
    ipAddress: "192.168.1.112",
    metadata: { domain: "staging.booknest.in", reason: "cleanup" },
    createdAt: "2025-01-13T09:30:00Z",
  },
  {
    id: "log_021",
    userId: "usr_006",
    userName: "Vikram Singh",
    action: "UPDATE",
    entityType: "Subscription",
    entityId: "sub_089",
    details: "Subscription plan price overridden for HomeEssentials Mart — ₹3,999/mo (was ₹4,999)",
    ipAddress: "192.168.1.120",
    metadata: { originalPrice: 4999, customPrice: 3999, overrideReason: "Long-term customer discount" },
    createdAt: "2025-01-12T16:45:00Z",
  },
  {
    id: "log_022",
    userId: "usr_001",
    userName: "Priya Sharma",
    action: "CREATE",
    entityType: "Invoice",
    entityId: "inv_067",
    details: "Invoice INV-25/01/067 generated for FreshMart Grocers — ₹4,999.00 monthly billing",
    ipAddress: "192.168.1.105",
    metadata: { invoiceType: "TAX_INVOICE", amount: 4999, gstAmount: 899.82 },
    createdAt: "2025-01-12T10:00:00Z",
  },
  {
    id: "log_023",
    userId: "usr_004",
    userName: "Amit Patel",
    action: "LOGOUT",
    entityType: "User",
    entityId: "usr_004",
    details: "User logged out after 4h 20m session",
    ipAddress: "49.207.55.88",
    metadata: { sessionDuration: "4h 20m" },
    createdAt: "2025-01-12T09:00:00Z",
  },
  {
    id: "log_024",
    userId: "usr_005",
    userName: "Sneha Iyer",
    action: "UPDATE",
    entityType: "Order",
    entityId: "ord_880",
    details: "Delivery address updated for order FM-20250112-003 by customer Mohan Sharma",
    ipAddress: "157.49.22.11",
    metadata: { previousAddress: "23, Hill View Road, Bandra", newAddress: "512, Biz Tower, BKC" },
    createdAt: "2025-01-11T18:30:00Z",
  },
  {
    id: "log_025",
    userId: "usr_003",
    userName: "Admin System",
    action: "STATUS_CHANGE",
    entityType: "Business",
    entityId: "biz_022",
    details: "Business status changed from ONBOARDING to ACTIVE for PetPals Store",
    ipAddress: "10.0.0.1",
    metadata: { previousStatus: "ONBOARDING", newStatus: "ACTIVE", activatedAt: "2025-01-11T17:00:00Z" },
    createdAt: "2025-01-11T17:00:00Z",
  },
  {
    id: "log_026",
    userId: "usr_002",
    userName: "Rahul Verma",
    action: "CREATE",
    entityType: "Store",
    entityId: "store_015",
    details: "New store 'FreshMart - Powai' added for FreshMart Grocers",
    ipAddress: "192.168.1.112",
    metadata: { storeName: "FreshMart - Powai", city: "Mumbai", posEnabled: true },
    createdAt: "2025-01-11T14:20:00Z",
  },
  {
    id: "log_027",
    userId: "usr_006",
    userName: "Vikram Singh",
    action: "EXPORT",
    entityType: "Business",
    entityId: "batch_013",
    details: "Exported business list — 28 active businesses as CSV",
    ipAddress: "192.168.1.120",
    metadata: { format: "CSV", recordCount: 28, includes: ["name", "type", "status", "revenue"] },
    createdAt: "2025-01-11T11:45:00Z",
  },
  {
    id: "log_028",
    userId: "usr_001",
    userName: "Priya Sharma",
    action: "PAYMENT",
    entityType: "Payment",
    entityId: "pay_183",
    details: "Payment verification completed for GreenLeaf Organics — ₹49,999 yearly plan",
    ipAddress: "192.168.1.105",
    metadata: { amount: 49999, billingCycle: "YEARLY", verifiedBy: "usr_001" },
    createdAt: "2025-01-10T16:30:00Z",
  },
  {
    id: "log_029",
    userId: "usr_005",
    userName: "Sneha Iyer",
    action: "DELETE",
    entityType: "Customer",
    entityId: "cust_312",
    details: "Customer account deleted per GDPR request — account #cust_312",
    ipAddress: "192.168.1.108",
    metadata: { reason: "GDPR deletion request", dataWiped: true },
    createdAt: "2025-01-10T13:00:00Z",
  },
  {
    id: "log_030",
    userId: "usr_003",
    userName: "Admin System",
    action: "CONFIG",
    entityType: "Business",
    entityId: "biz_001",
    details: "Notification preferences updated for FreshMart Grocers — WhatsApp enabled for order status",
    ipAddress: "10.0.0.1",
    metadata: { channel: "WHATSAPP", eventType: "ORDER_STATUS", enabled: true },
    createdAt: "2025-01-10T10:15:00Z",
  },
];
