// Prints the Laundry OS permission matrix from the code that enforces it.
//
//   npx tsx scripts/rbac-matrix.ts            → role × screen matrix
//   npx tsx scripts/rbac-matrix.ts --guards   → screen → API guard inventory
//   npx tsx scripts/rbac-matrix.ts --md       → markdown (docs/LAUNDRY_RBAC_MATRIX.md)
//
// Nothing is transcribed by hand: roles come from SYSTEM_ROLES, screens from
// SCREEN_MODULES, navigation from defaultNavigationConfig() and the guards are
// read out of the route sources. A matrix written in prose goes stale; this one
// cannot.
//
// Delivery Executive is listed but marked out of scope — it is a separate PWA
// with its own session model.

import { readFileSync, readdirSync, statSync, writeFileSync } from "fs"
import { join } from "path"
import { SYSTEM_ROLES } from "../src/lib/laundry-rbac-catalog"
import { SCREEN_MODULES, allScreenKeys, isValidScreenKey, permKeyToScreenLevel, Level } from "../src/lib/laundry-rbac-registry"
import { defaultNavigationConfig, SCREEN_PAGE_MAP } from "../src/lib/laundry-nav-config"
import { ROLE_ADMIN_SCREEN, ROLE_READ_SCREENS } from "../src/lib/laundry-rbac-screens"
import { WORKSTATION_SCREEN_KEYS as WORKSTATION_SCREENS } from "../src/lib/permission-sync"

/** Guard keys written as a shared constant rather than a literal. */
const SHARED_GUARD_CONSTANTS: Record<string, string[]> = {
  ROLE_ADMIN_SCREEN: [ROLE_ADMIN_SCREEN],
  ROLE_READ_SCREENS,
}

const OUT_OF_SCOPE = new Set(["DELIVERY_EXECUTIVE"])
const LVL = ["—", "View", "Create", "Edit"]

const levelsOf = (code: string) => {
  const def = SYSTEM_ROLES.find((r) => r.code === code)!
  const m = new Map<string, number>()
  if (def.isOwner) { for (const k of allScreenKeys()) m.set(k, Level.EDIT); return m }
  for (const s of def.screens()) m.set(s.screenKey, Math.max(m.get(s.screenKey) ?? 0, s.level))
  return m
}

/** screenKey → the API routes guarding on it, with the level each requires. */
function guardInventory() {
  const walk = (d: string): string[] =>
    readdirSync(d).flatMap((n) => {
      const p = join(d, n)
      return statSync(p).isDirectory() ? walk(p) : n === "route.ts" ? [p] : []
    })
  const inv = new Map<string, Set<string>>()
  const invalid: string[] = []
  for (const f of walk("src/app/api/laundry")) {
    const s = readFileSync(f, "utf8")
    const route = f.replace("src/app/api/", "").replace("/route.ts", "")
    const record = (key: string, level: number) => {
      if (!isValidScreenKey(key)) { invalid.push(`${route}: ${key}`); return }
      if (!inv.has(key)) inv.set(key, new Set())
      inv.get(key)!.add(`${route} (${LVL[level]})`)
    }
    // Guards written against a shared constant, and the workstation guard built
    // from the stage, are real enforcement — expand them so the inventory does
    // not report their screens as ungoverned.
    for (const m of s.matchAll(/requireLaundry(?:Any)?Level\([^,]+,[^,]+,\s*(?:["'`]([^"'`$]+)["'`]|(\w+))\s*,\s*Level\.(\w+)/g)) {
      const level = Level[m[3] as keyof typeof Level] as number
      for (const k of m[1] ? [m[1]] : (SHARED_GUARD_CONSTANTS[m[2]] ?? [m[2]])) record(k, level)
    }
    for (const m of s.matchAll(/requireLaundryPermission\([^,]+,[^,]+,\s*["']([^"'$]+)["']/g)) {
      const mapped = permKeyToScreenLevel(m[1])
      if (mapped) record(mapped.screenKey, mapped.level)
      else invalid.push(`${route}: ${m[1]}`)
    }
    // /api/laundry/processing builds its key from the stage being worked.
    if (/processing\.\$\{STAGE_SCREEN/.test(s)) {
      for (const k of WORKSTATION_SCREENS) record(k, Level.VIEW)
    }
  }
  return { inv, invalid }
}

const navScreens = new Set(defaultNavigationConfig().flatMap((g) => g.items.map((i) => i.screenKey)))
const roles = SYSTEM_ROLES.map((r) => r.code)

function matrix(): string {
  const { inv, invalid } = guardInventory()
  const L: string[] = []
  L.push("# Laundry OS — Role & Permission Matrix")
  L.push("")
  L.push("Generated by `npx tsx scripts/rbac-matrix.ts --md`. Do not edit by hand.")
  L.push("")
  L.push("Levels: **View** read-only · **Create** create + workflow progression · **Edit** destructive/exceptional.")
  L.push("A blank cell means the role cannot see the screen or call its APIs.")
  L.push("")
  L.push("`Delivery Executive` is shown for completeness only — it is a separate PWA with its own session model and is out of scope for tenant RBAC changes.")
  L.push("")

  L.push("## Roles")
  L.push("")
  L.push("| Role | Screens | Scope |")
  L.push("|---|---|---|")
  for (const r of SYSTEM_ROLES) {
    const n = r.isOwner ? allScreenKeys().length : new Set(r.screens().map((s) => s.screenKey)).size
    L.push(`| ${r.name}${OUT_OF_SCOPE.has(r.code) ? " *(out of scope)*" : ""} | ${n} | ${r.description} |`)
  }
  L.push("")

  L.push("## Screen × Role")
  L.push("")
  L.push("`Nav` marks a screen that appears in the default sidebar. `Enforced by` lists the APIs that gate on it — a screen with navigation but no enforcing API is served by an endpoint gated on a different screen, which is noted where it matters.")
  L.push("")
  for (const mod of SCREEN_MODULES) {
    L.push(`### ${mod.label}`)
    L.push("")
    L.push(`| Screen | Nav | ${roles.map((r) => SYSTEM_ROLES.find((x) => x.code === r)!.name).join(" | ")} | Enforced by |`)
    L.push(`|---|---|${roles.map(() => "---").join("|")}|---|`)
    for (const sc of mod.screens) {
      const key = `${mod.key}.${sc.key}`
      const cells = roles.map((r) => LVL[levelsOf(r).get(key) ?? 0])
      const routes = [...(inv.get(key) ?? [])].sort()
      L.push(`| \`${key}\` ${sc.label} | ${navScreens.has(key) ? "✓" : ""} | ${cells.join(" | ")} | ${routes.length ? routes.join("<br>") : "—"} |`)
    }
    L.push("")
  }

  if (invalid.length) {
    L.push("## ⚠ Guards naming an unregistered screen")
    L.push("")
    L.push("These deny every role but the owner, because the key can never be granted.")
    L.push("")
    for (const i of invalid) L.push(`- \`${i}\``)
    L.push("")
  }

  L.push("## Pages without a landing route")
  L.push("")
  const noPage = allScreenKeys().filter((k) => !SCREEN_PAGE_MAP[k])
  L.push(noPage.length ? noPage.map((k) => `- \`${k}\``).join("\n") : "None.")
  L.push("")
  return L.join("\n")
}

function console_() {
  const { inv, invalid } = guardInventory()
  const w = 34
  console.log("SCREEN".padEnd(w) + "NAV  " + roles.map((r) => r.slice(0, 9).padEnd(10)).join(""))
  for (const mod of SCREEN_MODULES) {
    for (const sc of mod.screens) {
      const key = `${mod.key}.${sc.key}`
      const cells = roles.map((r) => LVL[levelsOf(r).get(key) ?? 0].padEnd(10))
      console.log(key.padEnd(w) + (navScreens.has(key) ? " ✓   " : "     ") + cells.join(""))
    }
  }
  if (process.argv.includes("--guards")) {
    console.log("\nSCREEN → ENFORCING ROUTES")
    for (const [k, v] of [...inv].sort()) console.log(`  ${k}\n    ${[...v].sort().join("\n    ")}`)
    const unenforced = allScreenKeys().filter((k) => !inv.has(k))
    console.log("\nSCREENS WITH NO API GUARDING ON THEM (served under another screen's key):")
    for (const k of unenforced) console.log(`  ${k}`)
  }
  if (invalid.length) {
    console.log("\n⚠ GUARDS ON UNREGISTERED KEYS (deny everyone but the owner):")
    for (const i of invalid) console.log(`  ${i}`)
  }
}

if (process.argv.includes("--md")) {
  const out = "docs/LAUNDRY_RBAC_MATRIX.md"
  writeFileSync(out, matrix())
  console.log(`wrote ${out}`)
} else {
  console_()
}
